service: serverless-graphql-apollo

frameworkVersion: ">=1.21.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: ap-southeast-2

plugins:
  - serverless-offline
  - serverless-webpack

custom:
  serverless-offline:
    port: 4000
    babelOptions:
      presets: ["es2015", "stage-2"]
  webpack: webpack.config.js
  webpackIncludeModules: true

functions:
  graphql:
    handler: handler
    events:
    - http:
        path: graphql
        method: post
        cors: true
